apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-push-pipeline
spec:
  description: |
    github-push-pipeline takes a git repository and a commit SHA
    and validates that cloning the revision succeeds. This is an example
    Pipeline demonstrating the following:
      - Using the git-clone catalog Task to clone a specific commit
      - Passing a cloned repo to subsequent Tasks using a Workspace.
      - Ordering Tasks in a Pipeline using "runAfter" so that
        git-clone completes before we try to read from the Workspace.
      - Using a volumeClaimTemplate Volume as a Workspace.
      - Avoiding hard-coded paths by using a Workspace's path
        variable instead.
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: commit
    type: string
    description: The git commit to fetch.
  - name: user-home
    type: string
    description: The home directory of the user performing the git clone.
    default: "/tekton/home"
  - name: user-uid
    type: string
    description: The UID of the user performing the git clone.
    default: "0"
  - name: image
    type: string
    description: The image name which will build
  - name: image_tag
    type: string
  - name: insecure_registry
    type: string
    description: The image registry
  - name: subdirectory
    type: string
    default: ""
  - name: revision
    type: string
    default: "master"
  - name: refspec
    type: string
    default: ""
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the commit to be checked.
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.commit)
    - name: refspec
      value: $(params.refspec)
    - name: userHome
      value: $(params.user-home)
    - name: deleteExisting
      value: "true"
    - name: subdirectory
      value: $(params.commit)
#  - name: run-test
#    taskRef:
#      name: golang-test
#    runAfter:
#      - fetch-repo
#    workspaces:
#      - name: source
#        workspace: shared-data
  - name: image-build-and-push
    taskRef:
      name: docker-build
    runAfter:
            #- run-test
      - fetch-repo
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: image
      value: $(params.image)
    - name: image_tag
      value: $(params.image_tag)
    - name: insecure_registry
      value: $(params.insecure_registry)
    - name: subpath
      value: $(params.commit)
  - name: fetch-deployment-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: http://opnfv.zte.com.cn/gerrit/openzero/sample-project
    - name: revision
      value: master
    - name: subdirectory
      value: master
    - name: deleteExisting
      value: "true"
    runAfter:
      - image-build-and-push
  - name: push-manifests
    taskRef:
      name: push-manifests
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: deployment-subdirectory
      value: helloworld
    - name: source-commit-id
      value: master
    - name: image
      value: $(params.image)
    - name: application
      value: helloworld
    - name: image_tag
      value: $(params.image_tag)
    runAfter:
      - fetch-deployment-repository