apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: git-clone-checking-out-a-commit
spec:
  pipelineRef:
    name: checking-out-a-revision
  workspaces:
  - name: shared-data
    persistentvolumeclaim:
      claimName: shared-task-storage
  taskRunSpecs:
  - pipelineTaskName: fetch-repo
    taskPodTemplate:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532 # nonroot user in git-init container
  params:
  - name: repo-url
    value: https://github.com/dongwenjuan/helloworld
  - name: commit
    value: ba5f4379d78b0dbf4f58b0aec7af9bb7f645fa2e
  - name: user-home
    value: "/home/nonroot"
  - name: user-uid
    value: "65532"
  - name: image
    value: harbor.oz/test/helloworld
  - name: insecure_registry
    value: harbor.oz