apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: git-clone-checking-out-a-commit-
spec:
  serviceAccountName: sshkey
  pipelineRef:
    name: github-push-pipeline
  workspaces:
  - name: shared-data
    persistentvolumeclaim:
      claimName: shared-task-storage
  taskRunSpecs:
  - pipelineTaskName: fetch-repo
    taskPodTemplate:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532 # nonroot user in git-init container
  params:
  - name: repo-url
    value: https://github.com/dongwenjuan/helloworld
  - name: commit
    value: 4e608a57e8a65678590ae9e475d103a4e24655ee
  - name: user-home
    value: "/home/nonroot"
  - name: user-uid
    value: "65532"
  - name: image
    value: harbor.oz/test/helloworld
  - name: image_tag
    value: v2
  - name: insecure_registry
    value: harbor.oz