---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-interceptor
spec:
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes:
              - push
      bindings:
        - ref: github-push-binding
      template:
        ref: github-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-github-sa
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-push-binding
spec:
  params:
    - name: gitrevision
      value: $(body.head.sha)
    - name: gitref
      value: $(body.ref)
    - name: gitrepositoryurl
      value: $(body.repo.url)
    - name: gitrepositoryname
      value: $(body.repo.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-template
spec:
  params:
    - name: commit
    - name: repo-url
    - name: refspec
    - name: user-home
    - name: user-uid
    - name: image
    - name: insecure_registry
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: git-clone-checking-out-a-commit
      spec:
        pipelineRef:
          name: github-push-pipeline
        workspaces:
        - name: shared-data
          persistentvolumeclaim:
            claimName: shared-task-storage
        taskRunSpecs:
        - pipelineTaskName: fetch-repo
          taskPodTemplate:
            securityContext:-
              runAsNonRoot: true
              runAsUser: 65532 # nonroot user in git-init container
        params:
        - name: repo-url
          value: $(tt.params.gitrepositoryurl)
        - name: refspec
          value: $(tt.params.gitref)
        - name: commit
          value: $(tt.params.gitrevision)
        - name: user-home
          value: "/home/nonroot"
        - name: user-uid
          value: "65532"
        - name: image
          value: harbor.oz/$(tt.params.gitrepositoryname)
        - name: insecure_registry
          value: harbor.oz
