apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: el-gerrit-listener-interceptor
spec:
  rules:
  - host: gerritlistener.oz
    http:
      paths:
      - backend:
          serviceName: el-gerrit-listener-interceptor
          servicePort: 8080